[project]
name = "docker"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "TomoTom0", email = "tomoIris427+GitHub@gmail.com" }
]
dependencies = [
    "requests>=2.32.3",
    "python-dotenv>=1.1.0",
    "bs4>=0.0.2",
    "pandas>=2.2.3",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.rye.scripts]
main = "rye run python src/ygo_db_update/ygo_db_update.py"
not-reuse = "rye run python src/ygo_db_update/ygo_db_update.py --not-reuse"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/docker"]
